---
- name: Copy index.html to prod
  hosts: tag_Prod
  become: yes
  tasks:
    - name: Copy index.html
      ansible.builtin.copy:
        src: ../website/index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
