---
- name: Restore default Apache DocumentRoot
  hosts: tag_webserver
  become: yes

  tasks:
    - name: Restore default VirtualHost
      copy:
        dest: /etc/apache2/sites-available/000-default.conf
        content: |
          <VirtualHost *:80>
              ServerAdmin webmaster@localhost
              DocumentRoot /var/www/html

              <Directory /var/www/html>
                  Options Indexes FollowSymLinks
                  AllowOverride None
                  Require all granted
              </Directory>

              ErrorLog ${APACHE_LOG_DIR}/error.log
              CustomLog ${APACHE_LOG_DIR}/access.log combined
          </VirtualHost>
      notify:
        - Reload Apache

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded


